// This file is generated from shared/frontend_core.js by tools/sync_shared.py.
// Do not edit this file directly.

const PROXY_ENDPOINT = "http://localhost:8000/zotero";
const BIB_ENDPOINT = "http://localhost:8000/bibliography";
const HEALTH_ENDPOINT = "http://localhost:8000/health";
const DEFAULT_BIBLIOGRAPHY_STYLE = "journal-of-geophysical-research-atmospheres";
const BIBLIOGRAPHY_STYLE_STORAGE_KEY = "zotero-ppt:bibliography-style";
const ZOTERO_TAG_KEY = "ZOTERO_CITATION_KEYS";

const LOG_LEVELS = {
  NONE: 0,
  ERROR: 1,
  WARN: 2,
  INFO: 3,
  DEBUG: 4,
};

const LOG_LEVEL = LOG_LEVELS.WARN;

function logDebug(...args) {
  if (LOG_LEVEL >= LOG_LEVELS.DEBUG) {
    console.log("[DEBUG]", ...args);
  }
}

function logInfo(...args) {
  if (LOG_LEVEL >= LOG_LEVELS.INFO) {
    console.log("[INFO]", ...args);
  }
}

function logWarn(...args) {
  if (LOG_LEVEL >= LOG_LEVELS.WARN) {
    console.warn("[WARN]", ...args);
  }
}

function logError(...args) {
  if (LOG_LEVEL >= LOG_LEVELS.ERROR) {
    console.error("[ERROR]", ...args);
  }
}

function log(...args) {
  logInfo(...args);
}

let healthIntervalId = null;

Office.onReady((info) => {
  if (info.host !== Office.HostType.PowerPoint) {
    logWarn("This add-in is built for PowerPoint. Current host:", info.host);
    return;
  }

  const wireEvents = () => {
    const addBtn = document.getElementById("add-citation");
    const addSelectedBtn = document.getElementById("add-citation-selected");
    const bibBtn = document.getElementById("generate-bibliography");
    const bibliographyStyleSelect = document.getElementById("bibliography-style");
    const output = document.getElementById("output");

    if (!addBtn || !bibBtn || !output) {
      logError("UI elements not found in the DOM. Check that scripts load after HTML body.");
      return;
    }

    addBtn.addEventListener("click", handleAddCitation);
    if (addSelectedBtn) {
      addSelectedBtn.addEventListener("click", handleAddCitationSelected);
    }
    bibBtn.addEventListener("click", handleGenerateBibliography);
    if (bibliographyStyleSelect) {
      initializeBibliographyStyleSelect(bibliographyStyleSelect);
      bibliographyStyleSelect.addEventListener("change", handleBibliographyStyleChange);
    }
    output.addEventListener("click", handleRemoveClick);

    Office.context.document.addHandlerAsync(
      Office.EventType.DocumentSelectionChanged,
      displayCitationsFromSlide,
      (asyncResult) => {
        if (asyncResult.status === Office.AsyncResultStatus.Failed) {
          logError("Could not register selection change handler: " + asyncResult.error.message);
        }
      }
    );

    displayCitationsFromSlide();
    startHealthPolling();
  };

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", wireEvents, { once: true });
  } else {
    wireEvents();
  }
});

async function handleAddCitation() {
  const xhr = new XMLHttpRequest();
  xhr.open("GET", PROXY_ENDPOINT, true);
  xhr.onreadystatechange = function () {
    if (xhr.readyState === 4) {
      if (xhr.status === 200) {
        try {
          const response = JSON.parse(xhr.responseText);
          log("Zotero response:", response);
          insertCitationsIntoPowerPoint(response);
        } catch (error) {
          logError("Error parsing JSON response:", error);
          document.getElementById("output").textContent = "Error: Could not parse Zotero data.";
        }
      } else {
        logError("Request failed with status:", xhr.status);
        document.getElementById("output").textContent = `Error: Could not connect to Zotero (Status: ${xhr.status}).`;
      }
    }
  };
  xhr.onerror = function () {
    logError("Request failed");
    document.getElementById("output").textContent = "Error: Request to Zotero proxy failed. Is it running?";
  };
  xhr.send();
}

async function handleAddCitationSelected() {
  const xhr = new XMLHttpRequest();
  xhr.open("GET", PROXY_ENDPOINT + "?selected=true", true);
  xhr.onreadystatechange = function () {
    if (xhr.readyState === 4) {
      if (xhr.status === 200) {
        try {
          const response = JSON.parse(xhr.responseText);
          log("Zotero response (selected):", response);
          insertCitationsIntoPowerPoint(response);
        } catch (error) {
          logError("Error parsing JSON response:", error);
          document.getElementById("output").textContent = "Error: Could not parse Zotero data.";
        }
      } else {
        logError("Request failed with status:", xhr.status);
        document.getElementById("output").textContent = `Error: Could not connect to Zotero (Status: ${xhr.status}).`;
      }
    }
  };
  xhr.onerror = function () {
    logError("Request failed");
    document.getElementById("output").textContent = "Error: Request to Zotero proxy failed. Is it running?";
  };
  xhr.send();
}

async function checkHealthOnce() {
  const statusEl = document.getElementById("status");
  if (!statusEl) {
    return;
  }

  try {
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 2500);
    const resp = await fetch(HEALTH_ENDPOINT, { signal: controller.signal });
    clearTimeout(timeout);

    if (resp.ok) {
      statusEl.textContent = "Zotero proxy connected";
      statusEl.className = "status ok";
    } else {
      statusEl.textContent = "Proxy unreachable (" + resp.status + ")";
      statusEl.className = "status error";
    }
  } catch (error) {
    statusEl.textContent = "Proxy not running";
    statusEl.className = "status error";
  }
}

function startHealthPolling() {
  const statusEl = document.getElementById("status");
  if (!statusEl) {
    return;
  }

  checkHealthOnce();
  if (healthIntervalId !== null) {
    return;
  }
  healthIntervalId = window.setInterval(checkHealthOnce, 8000);
}

function initializeBibliographyStyleSelect(selectElement) {
  const savedStyle = window.localStorage.getItem(BIBLIOGRAPHY_STYLE_STORAGE_KEY);
  const initialStyle = savedStyle || DEFAULT_BIBLIOGRAPHY_STYLE;
  let hasOption = false;
  for (let index = 0; index < selectElement.options.length; index += 1) {
    if (selectElement.options[index].value === initialStyle) {
      hasOption = true;
      break;
    }
  }
  selectElement.value = hasOption ? initialStyle : DEFAULT_BIBLIOGRAPHY_STYLE;
}

function handleBibliographyStyleChange(event) {
  const nextStyle = event.target.value || DEFAULT_BIBLIOGRAPHY_STYLE;
  window.localStorage.setItem(BIBLIOGRAPHY_STYLE_STORAGE_KEY, nextStyle);
}

function getSelectedBibliographyStyle() {
  const selectElement = document.getElementById("bibliography-style");
  if (selectElement instanceof HTMLSelectElement && selectElement.value) {
    return selectElement.value;
  }

  return window.localStorage.getItem(BIBLIOGRAPHY_STYLE_STORAGE_KEY) || DEFAULT_BIBLIOGRAPHY_STYLE;
}

function handleRemoveClick(event) {
  const removeButton = event.target.closest(".remove-btn");
  if (removeButton) {
    const keyToRemove = removeButton.dataset.key;
    if (keyToRemove) {
      removeCitation(keyToRemove);
    }
  }
}

async function handleGenerateBibliography() {
  const outputElement = document.getElementById("output");
  outputElement.textContent = "Generating bibliography...";

  try {
    const allCitationKeys = new Set();

    await PowerPoint.run(async (context) => {
      const slides = context.presentation.slides;
      slides.load("items");
      await context.sync();

      for (const slide of slides.items) {
        slide.tags.load("key, value");
      }
      await context.sync();

      for (const slide of slides.items) {
        const zoteroTag = slide.tags.items.find((tag) => tag.key === ZOTERO_TAG_KEY);
        if (zoteroTag) {
          try {
            const keysArray = JSON.parse(zoteroTag.value);
            if (Array.isArray(keysArray)) {
              keysArray.forEach((key) => allCitationKeys.add(key));
            }
          } catch (error) {
            logWarn("Could not parse citation keys on a slide", error);
          }
        }
      }
    });

    const uniqueKeys = Array.from(allCitationKeys);
    log("Found unique citation keys:", uniqueKeys);

    if (uniqueKeys.length === 0) {
      outputElement.textContent = "No citations found in the presentation.";
      return;
    }

    const formattedBibliography = await fetchBibliographyFromServer(uniqueKeys, getSelectedBibliographyStyle());
    await addBibliographySlide(formattedBibliography);

    outputElement.textContent = "Bibliography generated successfully!";
  } catch (error) {
    logError("Error generating bibliography:", error);
    outputElement.textContent = "Error: Could not generate bibliography.";
  }
}

function formatSingleCitation(item) {
  const creators = item.item.creators;
  const date = item.item.date || "";
  const year = extractYearFromDate(date);

  let authorString = "Unknown Author";
  if (creators && creators.length > 0) {
    if (creators.length === 1) {
      authorString = creators[0].lastName;
    } else if (creators.length === 2) {
      authorString = `${creators[0].lastName} & ${creators[1].lastName}`;
    } else {
      authorString = `${creators[0].lastName} et al.`;
    }
  }
  return `${authorString}, ${year}`;
}

function extractYearFromDate(dateStr) {
  if (!dateStr || typeof dateStr !== "string") {
    return "n.d.";
  }

  const isoMatch = /^(\d{4})[-/]/.exec(dateStr);
  if (isoMatch) {
    return isoMatch[1];
  }

  const yearMatch = /(1[5-9]\d{2}|20\d{2})/.exec(dateStr);
  if (yearMatch) {
    return yearMatch[1];
  }

  const parsed = new Date(dateStr);
  if (!isNaN(parsed.getTime())) {
    const year = parsed.getFullYear();
    if (year > 1500 && year < 2100) {
      return String(year);
    }
  }

  return "n.d.";
}

async function fetchBibliographyFromServer(keys, style) {
  const response = await fetch(BIB_ENDPOINT, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({ keys, style }),
  });

  if (!response.ok) {
    const errorData = await response.json();
    throw new Error(errorData.error || `Server responded with status: ${response.status}`);
  }

  const data = await response.json();
  return data.bibliography;
}

async function insertCitationsIntoPowerPoint(zoteroItems) {
  try {
    await PowerPoint.run(async (context) => {
      const slides = context.presentation.getSelectedSlides();
      slides.load("items");
      await context.sync();

      if (slides.items.length === 0) {
        logError("No slide selected.");
        document.getElementById("output").textContent = "Please select a slide first.";
        return;
      }
      const slide = slides.items[0];

      if (!Array.isArray(zoteroItems) || zoteroItems.length === 0) {
        log("No valid citation items found in the response.");
        document.getElementById("output").textContent = "No citations found to insert.";
        return;
      }

      const customTags = slide.tags;
      customTags.load("key, value");
      await context.sync();

      const existingTag = customTags.items.find((tag) => tag.key === ZOTERO_TAG_KEY);
      const citationKeys = new Set();

      if (existingTag) {
        try {
          const keysArray = JSON.parse(existingTag.value);
          if (Array.isArray(keysArray)) {
            keysArray.forEach((key) => citationKeys.add(key));
          }
        } catch (error) {
          logError("Could not parse existing citation tags:", error);
        }
      }
      zoteroItems.forEach((item) => citationKeys.add(item.citationKey));

      const updatedKeysArray = Array.from(citationKeys);
      slide.tags.add(ZOTERO_TAG_KEY, JSON.stringify(updatedKeysArray));

      const citationParts = zoteroItems.map((item) => formatSingleCitation(item));
      const citationsText = `(${citationParts.join("; ")})`;

      try {
        const selectedTextRange = context.presentation.getSelectedTextRange();
        selectedTextRange.load("text");
        await context.sync();

        const originalText = selectedTextRange.text;
        selectedTextRange.text = originalText + " " + citationsText;
        await context.sync();
      } catch (error) {
        if (error.name === "RichApi.Error" && error.code === "GeneralException") {
          log("No text range selected. Creating a new text box.");
          const textBox = slide.shapes.addTextBox(citationsText, {
            left: 100,
            top: 150,
            width: 400,
            height: 50,
          });
          textBox.load("textFrame/textRange");
          await context.sync();
        } else {
          logError("An unexpected error occurred during text insertion:", error);
          throw error;
        }
      }
    });

    await displayCitationsFromSlide();
  } catch (error) {
    logError("Error interacting with PowerPoint:", error);
    document.getElementById("output").textContent = "Error: Could not insert citations.";
  }
}

async function removeCitation(keyToRemove) {
  try {
    await PowerPoint.run(async (context) => {
      const slide = context.presentation.getSelectedSlides().getItemAt(0);
      const customTags = slide.tags;
      customTags.load("key, value");
      await context.sync();

      const zoteroTag = customTags.items.find((tag) => tag.key === ZOTERO_TAG_KEY);
      if (zoteroTag) {
        let currentKeys = [];
        try {
          currentKeys = JSON.parse(zoteroTag.value);
        } catch (error) {
          logError("Could not parse existing tags for removal:", error);
          return;
        }

        const updatedKeys = currentKeys.filter((key) => key !== keyToRemove);
        slide.tags.add(ZOTERO_TAG_KEY, JSON.stringify(updatedKeys));
        await context.sync();
      }
    });

    await displayCitationsFromSlide();
  } catch (error) {
    logError("Error removing citation:", error);
    document.getElementById("output").textContent = "Error: Could not remove citation.";
  }
}

async function displayCitationsFromSlide() {
  const outputElement = document.getElementById("output");
  outputElement.innerHTML = "";

  try {
    await PowerPoint.run(async (context) => {
      const slide = context.presentation.getSelectedSlides().getItemAt(0);
      if (!slide) {
        outputElement.textContent = "Select a slide to view its citations.";
        return;
      }

      const customTags = slide.tags;
      customTags.load("key, value");
      await context.sync();

      const zoteroTag = customTags.items.find((tag) => tag.key === ZOTERO_TAG_KEY);

      if (zoteroTag) {
        try {
          const keysArray = JSON.parse(zoteroTag.value);
          if (Array.isArray(keysArray) && keysArray.length > 0) {
            const header = document.createElement("p");
            header.textContent = "Citations on this slide:";
            const list = document.createElement("ul");

            keysArray.forEach((key) => {
              const listItem = document.createElement("li");
              const removeButton = document.createElement("button");
              removeButton.className = "remove-btn";
              removeButton.innerHTML = "&times;";
              removeButton.title = `Remove citation: ${key}`;
              removeButton.dataset.key = key;

              const keyText = document.createElement("span");
              keyText.className = "citation-key";
              keyText.textContent = key;

              listItem.appendChild(removeButton);
              listItem.appendChild(keyText);
              list.appendChild(listItem);
            });

            outputElement.replaceChildren(header, list);
          } else {
            outputElement.textContent = "No Zotero citations found on this slide.";
          }
        } catch (error) {
          logError("Error parsing citation tags from slide:", error);
          outputElement.textContent = "Error reading citations from this slide.";
        }
      } else {
        outputElement.textContent = "No Zotero citations found on this slide.";
      }
    });
  } catch (error) {
    logError("Error displaying citations from slide:", error);
    if (outputElement.innerHTML === "") {
      outputElement.textContent = "Could not load citations for this slide.";
    }
  }
}

async function addBibliographySlide(bibliographyText) {
  const trimmedBibliographyText = bibliographyText.replace(/\s+$/, "");

  await PowerPoint.run(async function (context) {
    const slideMasters = context.presentation.slideMasters.load("id, name, layouts/items/name, layouts/items/id");
    await context.sync();

    let targetMaster = slideMasters.items[0] || null;
    let layoutId = null;

    outer: for (const master of slideMasters.items) {
      for (const layout of master.layouts.items) {
        const layoutName = (layout.name || "").toLowerCase();
        if (layoutName === "title and content" || (layoutName.includes("title") && layoutName.includes("content"))) {
          targetMaster = master;
          layoutId = layout.id;
          break outer;
        }
      }
    }

    if (!targetMaster) {
      throw new Error("No slide master available for bibliography slide creation.");
    }

    if (!layoutId) {
      layoutId = targetMaster.layouts.items[1]?.id || targetMaster.layouts.items[0]?.id || null;
    }

    logInfo("loaded master");
    const newSlideOptions = {
      slideMasterId: targetMaster.id,
      ...(layoutId ? { layoutId } : {}),
    };

    context.presentation.slides.add(newSlideOptions);
    await context.sync();
    logInfo("inserted slide");

    const newSlideIndex = context.presentation.slides.getCount();
    await context.sync();

    context.presentation.load("slides");
    await context.sync();
    const newSlide = context.presentation.slides.getItemAt(newSlideIndex.value - 1);
    newSlide.load("id");
    await context.sync();

    try {
      let titleShape = null;
      let contentShape = null;

      newSlide.shapes.load("items/name");
      await context.sync();

      for (const shape of newSlide.shapes.items) {
        const name = (shape.name || "").toLowerCase();
        if (!titleShape && name.includes("title")) {
          titleShape = shape;
        } else if (!contentShape && (name.includes("content") || name.includes("body"))) {
          contentShape = shape;
        }
      }

      if (!titleShape && newSlide.shapes.items[0]) {
        titleShape = newSlide.shapes.items[0];
      }
      if (!contentShape && newSlide.shapes.items[1]) {
        contentShape = newSlide.shapes.items[1];
      }

      if (!titleShape) {
        throw new Error("No title shape found on new bibliography slide.");
      }

      titleShape.textFrame.textRange.text = "References";
      titleShape.textFrame.textRange.font.size = 44;

      if (!contentShape) {
        throw new Error("No content shape found on new bibliography slide.");
      }

      contentShape.textFrame.textRange.text = trimmedBibliographyText;
      contentShape.textFrame.textRange.font.size = 14;
      contentShape.textFrame.autoSizeSetting = PowerPoint.ShapeAutoSize.autoSizeShapeToFitText;
    } catch (error) {
      logError("Error setting content:", error);

      const titleShape = newSlide.shapes.addTextBox("References", {
        left: 50,
        top: 50,
        width: 860,
        height: 100,
      });
      titleShape.textFrame.textRange.font.size = 44;

      const contentShape = newSlide.shapes.addTextBox(trimmedBibliographyText, {
        left: 50,
        top: 150,
        width: 860,
        height: 350,
      });
      contentShape.textFrame.textRange.font.size = 14;
      contentShape.textFrame.autoSizeSetting = PowerPoint.ShapeAutoSize.autoSizeShapeToFitText;
    }

    await context.sync();
  });
}
