// This file is generated from shared/frontend_core.js by tools/sync_shared.ps1.
// Do not edit this file directly.

const PROXY_ENDPOINT = "http://localhost:8000/zotero";
const BIB_ENDPOINT = "http://localhost:8000/bibliography";
const HEALTH_ENDPOINT = "http://localhost:8000/health";
const DEFAULT_BIBLIOGRAPHY_STYLE = "journal-of-geophysical-research-atmospheres";
const BIBLIOGRAPHY_STYLE_STORAGE_KEY = "zotero-ppt:bibliography-style";
const ZOTERO_TAG_KEY = "ZOTERO_CITATION_KEYS";
const ZOTERO_BIBLIOGRAPHY_TAG = "ZOTERO_BIBLIOGRAPHY";
const BIBLIOGRAPHY_TITLE = "References";

const LOG_LEVELS = {
  NONE: 0,
  ERROR: 1,
  WARN: 2,
  INFO: 3,
  DEBUG: 4,
};

const LOG_LEVEL = LOG_LEVELS.WARN;

function logDebug(...args) {
  if (LOG_LEVEL >= LOG_LEVELS.DEBUG) {
    console.log("[DEBUG]", ...args);
  }
}

function logInfo(...args) {
  if (LOG_LEVEL >= LOG_LEVELS.INFO) {
    console.log("[INFO]", ...args);
  }
}

function logWarn(...args) {
  if (LOG_LEVEL >= LOG_LEVELS.WARN) {
    console.warn("[WARN]", ...args);
  }
}

function logError(...args) {
  if (LOG_LEVEL >= LOG_LEVELS.ERROR) {
    console.error("[ERROR]", ...args);
  }
}

function log(...args) {
  logInfo(...args);
}

let healthIntervalId = null;

Office.onReady((info) => {
  if (info.host !== Office.HostType.PowerPoint) {
    logWarn("This add-in is built for PowerPoint. Current host:", info.host);
    return;
  }

  const wireEvents = () => {
    const addBtn = document.getElementById("add-citation");
    const addSelectedBtn = document.getElementById("add-citation-selected");
    const bibBtn = document.getElementById("generate-bibliography");
    const bibliographyStyleSelect = document.getElementById("bibliography-style");
    const output = document.getElementById("output");

    if (!addBtn || !bibBtn || !output) {
      logError("UI elements not found in the DOM. Check that scripts load after HTML body.");
      return;
    }

    addBtn.addEventListener("click", handleAddCitation);
    if (addSelectedBtn) {
      addSelectedBtn.addEventListener("click", handleAddCitationSelected);
    }
    bibBtn.addEventListener("click", handleGenerateBibliography);
    if (bibliographyStyleSelect) {
      initializeBibliographyStyleSelect(bibliographyStyleSelect);
      bibliographyStyleSelect.addEventListener("change", handleBibliographyStyleChange);
    }
    output.addEventListener("click", handleRemoveClick);

    Office.context.document.addHandlerAsync(
      Office.EventType.DocumentSelectionChanged,
      displayCitationsFromSlide,
      (asyncResult) => {
        if (asyncResult.status === Office.AsyncResultStatus.Failed) {
          logError("Could not register selection change handler: " + asyncResult.error.message);
        }
      }
    );

    displayCitationsFromSlide();
    startHealthPolling();
  };

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", wireEvents, { once: true });
  } else {
    wireEvents();
  }
});

async function handleAddCitation() {
  const xhr = new XMLHttpRequest();
  xhr.open("GET", PROXY_ENDPOINT, true);
  xhr.onreadystatechange = function () {
    if (xhr.readyState === 4) {
      if (xhr.status === 200) {
        try {
          const response = JSON.parse(xhr.responseText);
          log("Zotero response:", response);
          insertCitationsIntoPowerPoint(response);
        } catch (error) {
          logError("Error parsing JSON response:", error);
          document.getElementById("output").textContent = "Error: Could not parse Zotero data.";
        }
      } else {
        logError("Request failed with status:", xhr.status);
        document.getElementById("output").textContent = `Error: Could not connect to Zotero (Status: ${xhr.status}).`;
      }
    }
  };
  xhr.onerror = function () {
    logError("Request failed");
    document.getElementById("output").textContent = "Error: Request to Zotero proxy failed. Is it running?";
  };
  xhr.send();
}

async function handleAddCitationSelected() {
  const xhr = new XMLHttpRequest();
  xhr.open("GET", PROXY_ENDPOINT + "?selected=true", true);
  xhr.onreadystatechange = function () {
    if (xhr.readyState === 4) {
      if (xhr.status === 200) {
        try {
          const response = JSON.parse(xhr.responseText);
          log("Zotero response (selected):", response);
          insertCitationsIntoPowerPoint(response);
        } catch (error) {
          logError("Error parsing JSON response:", error);
          document.getElementById("output").textContent = "Error: Could not parse Zotero data.";
        }
      } else {
        logError("Request failed with status:", xhr.status);
        document.getElementById("output").textContent = `Error: Could not connect to Zotero (Status: ${xhr.status}).`;
      }
    }
  };
  xhr.onerror = function () {
    logError("Request failed");
    document.getElementById("output").textContent = "Error: Request to Zotero proxy failed. Is it running?";
  };
  xhr.send();
}

async function checkHealthOnce() {
  const statusEl = document.getElementById("status");
  if (!statusEl) {
    return;
  }

  try {
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 2500);
    const resp = await fetch(HEALTH_ENDPOINT, { signal: controller.signal });
    clearTimeout(timeout);

    if (resp.ok) {
      statusEl.textContent = "Zotero proxy connected";
      statusEl.className = "status ok";
    } else {
      statusEl.textContent = "Proxy unreachable (" + resp.status + ")";
      statusEl.className = "status error";
    }
  } catch (error) {
    statusEl.textContent = "Proxy not running";
    statusEl.className = "status error";
  }
}

function startHealthPolling() {
  const statusEl = document.getElementById("status");
  if (!statusEl) {
    return;
  }

  checkHealthOnce();
  if (healthIntervalId !== null) {
    return;
  }
  healthIntervalId = window.setInterval(checkHealthOnce, 8000);
}

function initializeBibliographyStyleSelect(selectElement) {
  const savedStyle = window.localStorage.getItem(BIBLIOGRAPHY_STYLE_STORAGE_KEY);
  const initialStyle = savedStyle || DEFAULT_BIBLIOGRAPHY_STYLE;
  let hasOption = false;
  for (let index = 0; index < selectElement.options.length; index += 1) {
    if (selectElement.options[index].value === initialStyle) {
      hasOption = true;
      break;
    }
  }
  selectElement.value = hasOption ? initialStyle : DEFAULT_BIBLIOGRAPHY_STYLE;
}

function handleBibliographyStyleChange(event) {
  const nextStyle = event.target.value || DEFAULT_BIBLIOGRAPHY_STYLE;
  window.localStorage.setItem(BIBLIOGRAPHY_STYLE_STORAGE_KEY, nextStyle);
}

function getSelectedBibliographyStyle() {
  const selectElement = document.getElementById("bibliography-style");
  if (selectElement instanceof HTMLSelectElement && selectElement.value) {
    return selectElement.value;
  }

  return window.localStorage.getItem(BIBLIOGRAPHY_STYLE_STORAGE_KEY) || DEFAULT_BIBLIOGRAPHY_STYLE;
}

function handleRemoveClick(event) {
  const removeButton = event.target.closest(".remove-btn");
  if (removeButton) {
    const keyToRemove = removeButton.dataset.key;
    if (keyToRemove) {
      removeCitation(keyToRemove);
    }
  }
}

async function collectCitationKeysFromSlides() {
  const allCitationKeys = new Set();

  await PowerPoint.run(async (context) => {
    const slides = context.presentation.slides;
    slides.load("items");
    await context.sync();

    for (const slide of slides.items) {
      slide.tags.load("key, value");
    }
    await context.sync();

    for (const slide of slides.items) {
      const zoteroTag = slide.tags.items.find((tag) => tag.key === ZOTERO_TAG_KEY);
      if (zoteroTag) {
        try {
          const keysArray = JSON.parse(zoteroTag.value);
          if (Array.isArray(keysArray)) {
            keysArray.forEach((key) => allCitationKeys.add(key));
          }
        } catch (error) {
          logWarn("Could not parse citation keys on a slide", error);
        }
      }
    }
  });

  return Array.from(allCitationKeys);
}

/* A key that BBT cannot resolve (renamed or deleted item) renders as nothing, so every key is
   checked on its own. A failed check is not reported as a missing key. */
async function findMissingCitationKeys(keys, style) {
  const results = await Promise.all(
    keys.map(async (key) => {
      try {
        const text = await fetchBibliographyFromServer([key], style, "text");
        return typeof text === "string" && text.trim().length > 0 ? null : key;
      } catch (error) {
        logWarn("Could not check citation key", key, error);
        return null;
      }
    }),
  );
  return results.filter((key) => key !== null);
}

async function handleGenerateBibliography() {
  const outputElement = document.getElementById("output");
  outputElement.textContent = "Generating bibliography...";

  try {
    const uniqueKeys = await collectCitationKeysFromSlides();
    log("Found unique citation keys:", uniqueKeys);

    if (uniqueKeys.length === 0) {
      outputElement.textContent = "No citations found in the presentation.";
      return;
    }

    const style = getSelectedBibliographyStyle();
    const missingKeys = await findMissingCitationKeys(uniqueKeys, style);
    const bibliographyHtml = await fetchBibliographyFromServer(uniqueKeys, style, "html");
    const bibliography = parseFormattedBibliography(bibliographyHtml);

    if (!bibliography.text) {
      outputElement.textContent = "Zotero returned an empty bibliography.";
      return;
    }

    await writeBibliographySlide(bibliography);

    outputElement.textContent = missingKeys.length > 0
      ? `Bibliography generated. Not found in Zotero: ${missingKeys.join(", ")}`
      : "Bibliography generated successfully!";
  } catch (error) {
    logError("Error generating bibliography:", error);
    const detail = error && error.message ? " (" + error.message + ")" : "";
    outputElement.textContent = "Error: Could not generate bibliography." + detail;
  }
}

/* The Zotero picker's extra fields ("see ", "p. 42", suppress author) arrive next to the item or
   inside it, so both are checked. */
function pickerField(item, name) {
  const sources = [item, item ? item.item : null];
  for (const source of sources) {
    if (!source) continue;
    const value = source[name];
    if (value !== undefined && value !== null && value !== "") {
      return String(value);
    }
  }
  return "";
}

function formatSingleCitation(item) {
  const creators = item.item.creators;
  const date = item.item.date || "";
  const year = extractYearFromDate(date);

  const suppressAuthor = ["true", "1"].includes(
    pickerField(item, "suppressAuthor") || pickerField(item, "suppress author"),
  );
  const locator = pickerField(item, "locator");
  const prefix = pickerField(item, "prefix");
  const suffix = pickerField(item, "suffix");

  let citation = year;
  if (!suppressAuthor) {
    let authorString = "Unknown Author";
    if (creators && creators.length > 0) {
      if (creators.length === 1) {
        authorString = creators[0].lastName;
      } else if (creators.length === 2) {
        authorString = `${creators[0].lastName} & ${creators[1].lastName}`;
      } else {
        authorString = `${creators[0].lastName} et al.`;
      }
    }
    citation = `${authorString}, ${year}`;
  }

  if (locator) citation += `, ${locator}`;
  if (suffix) citation += `, ${suffix}`;
  if (prefix) citation = `${prefix} ${citation}`;
  return citation;
}

function extractYearFromDate(dateStr) {
  if (!dateStr || typeof dateStr !== "string") {
    return "n.d.";
  }

  const isoMatch = /^(\d{4})[-/]/.exec(dateStr);
  if (isoMatch) {
    return isoMatch[1];
  }

  const yearMatch = /(1[5-9]\d{2}|20\d{2})/.exec(dateStr);
  if (yearMatch) {
    return yearMatch[1];
  }

  const parsed = new Date(dateStr);
  if (!isNaN(parsed.getTime())) {
    const year = parsed.getFullYear();
    if (year > 1500 && year < 2100) {
      return String(year);
    }
  }

  return "n.d.";
}

async function fetchBibliographyFromServer(keys, style, format) {
  const response = await fetch(BIB_ENDPOINT, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({ keys, style, format: format || "text" }),
  });

  if (!response.ok) {
    const errorData = await response.json();
    throw new Error(errorData.error || `Server responded with status: ${response.status}`);
  }

  const data = await response.json();
  return data.bibliography;
}

async function insertCitationsIntoPowerPoint(zoteroItems) {
  try {
    await PowerPoint.run(async (context) => {
      const slides = context.presentation.getSelectedSlides();
      slides.load("items");
      await context.sync();

      if (slides.items.length === 0) {
        logError("No slide selected.");
        document.getElementById("output").textContent = "Please select a slide first.";
        return;
      }
      const slide = slides.items[0];

      if (!Array.isArray(zoteroItems) || zoteroItems.length === 0) {
        log("No valid citation items found in the response.");
        document.getElementById("output").textContent = "No citations found to insert.";
        return;
      }

      const customTags = slide.tags;
      customTags.load("key, value");
      await context.sync();

      const existingTag = customTags.items.find((tag) => tag.key === ZOTERO_TAG_KEY);
      const citationKeys = new Set();

      if (existingTag) {
        try {
          const keysArray = JSON.parse(existingTag.value);
          if (Array.isArray(keysArray)) {
            keysArray.forEach((key) => citationKeys.add(key));
          }
        } catch (error) {
          logError("Could not parse existing citation tags:", error);
        }
      }
      zoteroItems.forEach((item) => citationKeys.add(item.citationKey));

      const updatedKeysArray = Array.from(citationKeys);
      slide.tags.add(ZOTERO_TAG_KEY, JSON.stringify(updatedKeysArray));

      const citationParts = zoteroItems.map((item) => formatSingleCitation(item));
      const citationsText = `(${citationParts.join("; ")})`;

      try {
        const selectedTextRange = context.presentation.getSelectedTextRange();
        selectedTextRange.load("text");
        await context.sync();

        const originalText = selectedTextRange.text;
        selectedTextRange.text = originalText + " " + citationsText;
        await context.sync();
      } catch (error) {
        if (error.name === "RichApi.Error" && error.code === "GeneralException") {
          log("No text range selected. Creating a new text box.");
          const textBox = slide.shapes.addTextBox(citationsText, {
            left: 100,
            top: 150,
            width: 400,
            height: 50,
          });
          textBox.load("textFrame/textRange");
          await context.sync();
        } else {
          logError("An unexpected error occurred during text insertion:", error);
          throw error;
        }
      }
    });

    await displayCitationsFromSlide();
  } catch (error) {
    logError("Error interacting with PowerPoint:", error);
    document.getElementById("output").textContent = "Error: Could not insert citations.";
  }
}

async function removeCitation(keyToRemove) {
  try {
    await PowerPoint.run(async (context) => {
      const slide = context.presentation.getSelectedSlides().getItemAt(0);
      const customTags = slide.tags;
      customTags.load("key, value");
      await context.sync();

      const zoteroTag = customTags.items.find((tag) => tag.key === ZOTERO_TAG_KEY);
      if (zoteroTag) {
        let currentKeys = [];
        try {
          currentKeys = JSON.parse(zoteroTag.value);
        } catch (error) {
          logError("Could not parse existing tags for removal:", error);
          return;
        }

        const updatedKeys = currentKeys.filter((key) => key !== keyToRemove);
        slide.tags.add(ZOTERO_TAG_KEY, JSON.stringify(updatedKeys));
        await context.sync();
      }
    });

    await displayCitationsFromSlide();
  } catch (error) {
    logError("Error removing citation:", error);
    document.getElementById("output").textContent = "Error: Could not remove citation.";
  }
}

async function displayCitationsFromSlide() {
  const outputElement = document.getElementById("output");
  outputElement.innerHTML = "";

  try {
    await PowerPoint.run(async (context) => {
      const slide = context.presentation.getSelectedSlides().getItemAt(0);
      if (!slide) {
        outputElement.textContent = "Select a slide to view its citations.";
        return;
      }

      const customTags = slide.tags;
      customTags.load("key, value");
      await context.sync();

      const zoteroTag = customTags.items.find((tag) => tag.key === ZOTERO_TAG_KEY);

      if (zoteroTag) {
        try {
          const keysArray = JSON.parse(zoteroTag.value);
          if (Array.isArray(keysArray) && keysArray.length > 0) {
            const list = document.createElement("ul");

            keysArray.forEach((key) => {
              const listItem = document.createElement("li");
              const removeButton = document.createElement("button");
              removeButton.className = "remove-btn";
              removeButton.innerHTML = "&times;";
              removeButton.title = `Remove citation: ${key}`;
              removeButton.dataset.key = key;

              const keyText = document.createElement("span");
              keyText.className = "citation-key";
              keyText.textContent = key;

              listItem.appendChild(removeButton);
              listItem.appendChild(keyText);
              list.appendChild(listItem);
            });

            outputElement.replaceChildren(list);
          } else {
            outputElement.textContent = "No Zotero citations found on this slide.";
          }
        } catch (error) {
          logError("Error parsing citation tags from slide:", error);
          outputElement.textContent = "Error reading citations from this slide.";
        }
      } else {
        outputElement.textContent = "No Zotero citations found on this slide.";
      }
    });
  } catch (error) {
    logError("Error displaying citations from slide:", error);
    if (outputElement.innerHTML === "") {
      outputElement.textContent = "Could not load citations for this slide.";
    }
  }
}

/* BBT is asked for HTML because that is the only way to get real italics, bold, sub- and
   superscript out of Zotero. Only that small subset of tags is interpreted. */
const BIBLIOGRAPHY_FORMAT_TAGS = {
  i: "italic",
  em: "italic",
  b: "bold",
  strong: "bold",
  sub: "subscript",
  sup: "superscript",
  sc: "smallCaps",
};

const BIBLIOGRAPHY_LINE_BREAK_TAGS = { div: true, p: true, br: true, li: true, tr: true };

const HTML_ENTITIES = {
  nbsp: " ",
  amp: "&",
  lt: "<",
  gt: ">",
  quot: "\"",
  apos: "'",
  ndash: "\u2013",
  mdash: "\u2014",
  hellip: "\u2026",
  lsquo: "\u2018",
  rsquo: "\u2019",
  ldquo: "\u201c",
  rdquo: "\u201d",
  times: "\u00d7",
};

function decodeHtmlEntities(text) {
  return text
    .replace(/&#x([0-9a-f]+);/gi, (match, hex) => String.fromCodePoint(parseInt(hex, 16)))
    .replace(/&#(\d+);/g, (match, code) => String.fromCodePoint(parseInt(code, 10)))
    .replace(/&([a-z]+);/gi, (match, name) =>
      Object.prototype.hasOwnProperty.call(HTML_ENTITIES, name.toLowerCase())
        ? HTML_ENTITIES[name.toLowerCase()]
        : match,
    );
}

/* Turns the HTML bibliography into plain text plus the formatting runs that index into it,
   where the formatting is the flag set that must be applied to that slice of text. */
function parseFormattedBibliography(html) {
  const runs = [];
  const openFlags = [];
  let text = "";
  let pending = "";
  let pendingFormat = null;

  const flush = () => {
    if (pending.length > 0 && pendingFormat) {
      runs.push({ start: text.length - pending.length, length: pending.length, format: pendingFormat });
    }
    pending = "";
  };

  const append = (chunk, format) => {
    if (chunk.length === 0) return;
    const formatKey = format ? JSON.stringify(format) : "";
    const pendingKey = pendingFormat ? JSON.stringify(pendingFormat) : "";
    if (formatKey !== pendingKey) {
      flush();
      pendingFormat = format;
    }
    text += chunk;
    pending += chunk;
  };

  const tokens = String(html || "").match(/<[^>]*>|[^<]+/g) || [];
  for (const token of tokens) {
    if (token.charAt(0) === "<") {
      const tag = /^<\/?\s*([a-zA-Z0-9]+)/.exec(token);
      if (!tag) continue;
      const name = tag[1].toLowerCase();
      const closing = token.indexOf("</") === 0;

      if (BIBLIOGRAPHY_LINE_BREAK_TAGS[name]) {
        if (closing || name === "br") {
          flush();
          if (!text.endsWith("\n")) append("\n", null);
        }
        continue;
      }

      if (name === "span") {
        // Only small caps matters; </span> closes the matching <span>, whatever it pushed.
        if (closing) {
          const spanIndex = openFlags.lastIndexOf("smallCaps");
          if (spanIndex >= 0) openFlags.splice(spanIndex, 1);
        } else if (/small-caps/i.test(token)) {
          openFlags.push("smallCaps");
        }
        continue;
      }

      const flag = BIBLIOGRAPHY_FORMAT_TAGS[name];
      if (!flag) continue;

      if (closing) {
        const index = openFlags.lastIndexOf(flag);
        if (index >= 0) openFlags.splice(index, 1);
      } else if (token.indexOf("/>") !== token.length - 2) {
        openFlags.push(flag);
      }
      continue;
    }

    const format = {};
    for (const flag of openFlags) {
      format[flag] = true;
    }
    append(decodeHtmlEntities(token), openFlags.length > 0 ? format : null);
  }
  flush();

  return trimFormattedText(text, runs);
}

/* Drops surrounding whitespace while keeping the run offsets pointing at the same characters. */
function trimFormattedText(text, runs) {
  const leading = text.length - text.replace(/^\s+/, "").length;
  const trimmed = text.replace(/^\s+/, "").replace(/\s+$/, "");
  const end = leading + trimmed.length;
  const adjusted = [];
  for (const run of runs) {
    const start = Math.max(run.start, leading);
    const stop = Math.min(run.start + run.length, end);
    if (stop > start) {
      adjusted.push({ start: start - leading, length: stop - start, format: run.format });
    }
  }
  return { text: trimmed, runs: adjusted };
}

function applyBibliographyFormatting(textRange, runs) {
  for (const run of runs) {
    const substring = textRange.getSubstring(run.start, run.length);
    if (!substring) continue;
    const font = substring.font;
    if (run.format.italic) font.italic = true;
    if (run.format.bold) font.bold = true;
    if (run.format.subscript) font.subscript = true;
    if (run.format.superscript) font.superscript = true;
    if (run.format.smallCaps) font.smallCaps = true;
  }
}

async function addBibliographySlideFromMaster(context, slides) {
  const slideMasters = context.presentation.slideMasters.load("id, name, layouts/items/name, layouts/items/id");
  await context.sync();

  let targetMaster = slideMasters.items[0] || null;
  let layoutId = null;

  outer: for (const master of slideMasters.items) {
    for (const layout of master.layouts.items) {
      const layoutName = (layout.name || "").toLowerCase();
      if (layoutName === "title and content" || (layoutName.includes("title") && layoutName.includes("content"))) {
        targetMaster = master;
        layoutId = layout.id;
        break outer;
      }
    }
  }

  if (!targetMaster) {
    throw new Error("No slide master available for bibliography slide creation.");
  }
  if (!layoutId) {
    layoutId = (targetMaster.layouts.items[1] && targetMaster.layouts.items[1].id) || null;
  }
  if (!layoutId && targetMaster.layouts.items[0]) {
    layoutId = targetMaster.layouts.items[0].id;
  }

  const options = { slideMasterId: targetMaster.id };
  if (layoutId) options.layoutId = layoutId;
  slides.add(options);
  await context.sync();

  const count = slides.getCount();
  await context.sync();
  slides.load("items");
  await context.sync();
  return slides.getItemAt(count.value - 1);
}

/* An existing References slide is refreshed in place - first the one we tagged, then one whose
   title already says "References" - so pressing Generate twice never leaves two of them. */
async function findBibliographySlide(context, slides) {
  const tagged = slides.items.find((slide) =>
    slide.tags.items.some((tag) => tag.key === ZOTERO_BIBLIOGRAPHY_TAG),
  );
  if (tagged) return tagged;

  // The shape text must be loaded and synced before it can be read below.
  try {
    for (const slide of slides.items) {
      slide.shapes.load("items/name,items/textFrame/textRange/text");
    }
    await context.sync();
  } catch (error) {
    logWarn("Could not look for an existing References slide", error);
    return null;
  }

  const byTitle = slides.items.find((slide) =>
    slide.shapes.items.some((shape) => {
      const textFrame = shape.textFrame;
      const shapeText = textFrame && textFrame.textRange ? textFrame.textRange.text || "" : "";
      return shapeText.trim().toLowerCase() === BIBLIOGRAPHY_TITLE.toLowerCase();
    }),
  );
  return byTitle || null;
}


async function fillBibliographySlide(context, slide, bibliography) {
  slide.shapes.load("items/name");
  await context.sync();

  let titleShape = null;
  let contentShape = null;
  for (const shape of slide.shapes.items) {
    const name = (shape.name || "").toLowerCase();
    if (!titleShape && name.includes("title")) {
      titleShape = shape;
    } else if (!contentShape && (name.includes("content") || name.includes("body"))) {
      contentShape = shape;
    }
  }
  if (!titleShape && slide.shapes.items[0]) titleShape = slide.shapes.items[0];
  if (!contentShape && slide.shapes.items[1]) contentShape = slide.shapes.items[1];

  if (!titleShape) {
    titleShape = slide.shapes.addTextBox(BIBLIOGRAPHY_TITLE, { left: 50, top: 50, width: 860, height: 100 });
  }
  titleShape.textFrame.textRange.text = BIBLIOGRAPHY_TITLE;
  titleShape.textFrame.textRange.font.size = 44;

  if (!contentShape) {
    contentShape = slide.shapes.addTextBox("", { left: 50, top: 150, width: 860, height: 350 });
  }
  const textRange = contentShape.textFrame.textRange;
  textRange.text = bibliography.text;
  textRange.font.size = 14;
  applyBibliographyFormatting(textRange, bibliography.runs);
  contentShape.textFrame.autoSizeSetting = PowerPoint.ShapeAutoSize.autoSizeShapeToFitText;

  await context.sync();
}

async function writeBibliographySlide(bibliography) {
  await PowerPoint.run(async (context) => {
    const slides = context.presentation.slides;
    slides.load("items");
    await context.sync();

    for (const slide of slides.items) {
      slide.tags.load("key, value");
    }
    await context.sync();

    const existing = await findBibliographySlide(context, slides);

    const target = existing || (await addBibliographySlideFromMaster(context, slides));
    target.tags.add(ZOTERO_BIBLIOGRAPHY_TAG, "1");
    await context.sync();

    const position = slides.items.indexOf(target) + 1;
    if (position > 0 && position < slides.items.length) {
      logInfo("moving the bibliography slide to the end", position);
      target.moveTo(slides.items.length);
      await context.sync();
    }

    await fillBibliographySlide(context, target, bibliography);
  });
}
