"""Regenerates the copies of the shared frontend files from their sources.

shared/frontend_core.js -> script.js (Script Lab) + zotero-addon/www/frontend_core.js (add-in)
style.css               -> zotero-addon/www/style.css (add-in)
"""

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SHARED_FRONTEND = ROOT / "shared" / "frontend_core.js"
ROOT_STYLE = ROOT / "style.css"

FRONTEND_TARGETS = [
    ROOT / "script.js",
    ROOT / "zotero-addon" / "www" / "frontend_core.js",
]
STYLE_TARGETS = [
    ROOT / "zotero-addon" / "www" / "style.css",
]

FRONTEND_HEADER = (
    "// This file is generated from shared/frontend_core.js by tools/sync_shared.py.\n"
    "// Do not edit this file directly.\n\n"
)
STYLE_HEADER = "/* This file is generated from style.css by tools/sync_shared.py. Do not edit it directly. */\n"


def main():
    shared_source = SHARED_FRONTEND.read_text(encoding="utf-8").rstrip() + "\n"
    fresh_style = ROOT_STYLE.read_text(encoding="utf-8").rstrip() + "\n"

    for target in FRONTEND_TARGETS:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(FRONTEND_HEADER + shared_source, encoding="utf-8", newline="\n")
        print(f"Updated {target.relative_to(ROOT)}")

    for target in STYLE_TARGETS:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(STYLE_HEADER + fresh_style, encoding="utf-8", newline="\n")
        print(f"Updated {target.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
