<#
.SYNOPSIS
    Copies the shared frontend sources to the files that consume them.

.DESCRIPTION
    shared/frontend_core.js  ->  script.js (Script Lab) and zotero-addon/www/frontend_core.js (add-in)
    style.css                ->  zotero-addon/www/style.css (add-in)

    Afterwards run install.ps1 again so the installed copy gets the new files.

.EXAMPLE
    powershell -ExecutionPolicy Bypass -File .\tools\sync_shared.ps1
#>
[CmdletBinding()]
param([string]$Source)

if (-not $Source) { $Source = Split-Path -Parent $PSScriptRoot }
if (-not $Source) { $Source = Split-Path -Parent (Split-Path -Parent $PSCommandPath) }
if (-not $Source) { throw "Pass -Source <repository path>." }

$frontendPath = Join-Path $Source "shared\frontend_core.js"
$stylePath = Join-Path $Source "style.css"
foreach ($path in @($frontendPath, $stylePath)) {
    if (-not (Test-Path $path)) { throw "Not found: $path" }
}

$frontendHeader = "// This file is generated from shared/frontend_core.js by tools/sync_shared.ps1.`n// Do not edit this file directly.`n`n"
$styleHeader = "/* This file is generated from style.css by tools/sync_shared.ps1. Do not edit it directly. */`n"

# The repository keeps these files with LF endings, so write them back that way.
$frontendBody = (Get-Content $frontendPath -Raw).Replace("`r`n", "`n").TrimEnd() + "`n"
$styleBody = (Get-Content $stylePath -Raw).Replace("`r`n", "`n").TrimEnd() + "`n"

$targets = @(
    @{ Path = (Join-Path $Source "script.js"); Content = $frontendHeader + $frontendBody },
    @{ Path = (Join-Path $Source "zotero-addon\www\frontend_core.js"); Content = $frontendHeader + $frontendBody },
    @{ Path = (Join-Path $Source "zotero-addon\www\style.css"); Content = $styleHeader + $styleBody }
)

$utf8 = New-Object System.Text.UTF8Encoding($false)
foreach ($target in $targets) {
    [System.IO.File]::WriteAllText($target.Path, $target.Content, $utf8)
    Write-Host ("Updated " + $target.Path.Substring($Source.Length).TrimStart("\"))
}
