from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SHARED_FRONTEND = ROOT / "shared" / "frontend_core.js"

TARGETS = [
    ROOT / "script.js",
    ROOT / "zotero-addon" / "src" / "taskpane" / "taskpane.ts",
]

HEADER = "// This file is generated from shared/frontend_core.js by tools/sync_shared.py.\n// Do not edit this file directly.\n\n"


def main():
    shared_source = SHARED_FRONTEND.read_text(encoding="utf-8").rstrip() + "\n"
    output = HEADER + shared_source
    for target in TARGETS:
        target.write_text(output, encoding="utf-8", newline="\n")
        print(f"Updated {target.relative_to(ROOT)}")


if __name__ == "__main__":
    main()